### ISSUE TITLE
Attribute setting error in parserutils.py

### ISSUE THREAD

**Issue by MonkeyChap** [RDFLib/rdflib#1488]
Hi

The error reporting is a bit vague, so can't really tell what's causing this. However, we only get this error since upgrading to latest pip release of rdflib. The error goes away if we revert to an earlier version.

  File "/usr/local/lib/python3.8/site-packages/rdflib/graph.py", line 1127, in query
    result = plugin.get(result, query.Result)
  File "/usr/local/lib/python3.8/site-packages/rdflib/plugin.py", line 107, in get
    return p.getClass()
  File "/usr/local/lib/python3.8/site-packages/rdflib/plugin.py", line 69, in getClass
    module = __import__(self.module_path, globals(), locals(), [""])
  File "/usr/local/lib/python3.8/site-packages/rdflib/plugins/sparql/__init__.py", line 33, in <module>
    from . import parser
  File "/usr/local/lib/python3.8/site-packages/rdflib/plugins/sparql/parser.py", line 184, in <module>
    Param('prefix', PN_PREFIX)) + Suppress(':').leaveWhitespace()
  File "/usr/local/lib/python3.8/site-packages/rdflib/plugins/sparql/parserutils.py", line 114, in __init__
    self.name = name
AttributeError: can't set attribute

**Comment by aucampia** [comment]
I believe this is fixed on master branch, can you try the same with master branch and confirm?

**Comment by MonkeyChap** [comment]
Will do - thanks !  Might take a while to get back to you as we've been using pip in our build pipeline.

**Comment by MonkeyChap** [comment]
Turns out 6.0.1-alpha is available through pip. Error is still there.

**Comment by aucampia** [comment]
Pip can be told to run from git branch also (see [this](https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source)), I think the patch that fixed this error was this one: https://github.com/RDFLib/rdflib/pull/1409/files - actually would expect it to be in 6.0.1-alpha but I'm not sure.

**Comment by MonkeyChap** [comment]
Thanks - that looks like it fixes it.
